# https://docs.travis-ci.com/user/gui-and-headless-browsers/
notifications:
  email: false
language: node_js
dist: trusty
services:
  - mongodb
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
sudo: required
node_js:
  - "node"
# Install ffmpeg if needed
# No 16.04, need to install ffmpeg for trusty: https://github.com/travis-ci/travis-ci/issues/5821
#before_script:
#  - "sudo add-apt-repository -y ppa:mc3man/trusty-media"
#  - "sudo apt-get update"
#  - "sudo apt-get install -y ffmpeg"
script:
  # This is nasty because: https://github.com/travis-ci/travis-ci/issues/1066
  # Put the cd back to root to hack our way to fail fast
  # Video Service test wont work on travis: "Uncaught TypeError: Cannot read property 'socket' of undefined"
  #  - cd videoservice/lib && npm install && npm test && cd ../..
  - cd backend && npm install && npm test && cd ..
  - cd frontend && npm install && npm test && cd ..
