notifications:
  email: false
language: node_js
sudo: false
node_js:
  - "node"
before_install:
  - cd paint-with-bob
script:
  - cd frontend && npm install && npm test
  - cd backend && npm install && npm test
