# https://docs.travis-ci.com/user/gui-and-headless-browsers/
notifications:
  email: false
language: node_js
dist: trusty
services:
  - mongodb
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
sudo: required
node_js:
  - "node"
before_script:
  - "sudo aptitude -y -q install ffmpeg"
script:
  # This is nasty because: https://github.com/travis-ci/travis-ci/issues/1066
  - cd videoservice/lib && npm install && npm test && cd ../.. && cd backend && npm install && npm test && cd .. && cd frontend && npm install && npm test && cd ..
